// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_vivaviatravel2.Context;

#nullable disable

namespace api_vivaviatravel2._0.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240108223148_expandDB2")]
    partial class expandDB2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api_vivaviatravel2.Models.ClienteModel", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.HospedagemModel", b =>
                {
                    b.Property<int>("HospedagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospedagemId"), 1L, 1);

                    b.Property<decimal?>("Avaliacao")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeHotel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoDiaria")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("HospedagemId");

                    b.ToTable("Hospedagem");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.PacoteModel", b =>
                {
                    b.Property<int>("PacoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacoteId"), 1L, 1);

                    b.Property<int>("HospedagemId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PassagemId")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentDesconto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PacoteId");

                    b.HasIndex("HospedagemId");

                    b.HasIndex("PassagemId");

                    b.ToTable("Pacote");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.PassagemModel", b =>
                {
                    b.Property<int>("PassagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassagemId"), 1L, 1);

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataVoo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PassagemId");

                    b.ToTable("Passagem");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.ReservaModel", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("HospedagemId")
                        .HasColumnType("int");

                    b.Property<int?>("PacoteId")
                        .HasColumnType("int");

                    b.Property<int?>("PassagemId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HospedagemId");

                    b.HasIndex("PacoteId");

                    b.HasIndex("PassagemId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.PacoteModel", b =>
                {
                    b.HasOne("api_vivaviatravel2.Models.HospedagemModel", "Hospedagem")
                        .WithMany()
                        .HasForeignKey("HospedagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_vivaviatravel2.Models.PassagemModel", "Passagem")
                        .WithMany()
                        .HasForeignKey("PassagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospedagem");

                    b.Navigation("Passagem");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.ReservaModel", b =>
                {
                    b.HasOne("api_vivaviatravel2.Models.ClienteModel", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_vivaviatravel2.Models.HospedagemModel", "Hospedagem")
                        .WithMany("Reservas")
                        .HasForeignKey("HospedagemId");

                    b.HasOne("api_vivaviatravel2.Models.PacoteModel", "Pacote")
                        .WithMany("Reservas")
                        .HasForeignKey("PacoteId");

                    b.HasOne("api_vivaviatravel2.Models.PassagemModel", "Passagem")
                        .WithMany("Reservas")
                        .HasForeignKey("PassagemId");

                    b.Navigation("Cliente");

                    b.Navigation("Hospedagem");

                    b.Navigation("Pacote");

                    b.Navigation("Passagem");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.ClienteModel", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.HospedagemModel", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.PacoteModel", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("api_vivaviatravel2.Models.PassagemModel", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
